name: dragonfly
services:
  dragonfly:
    container_name: dragonfly
    build:
      context: ./dragonfly
      args:
        - PASSWORD=$PASSWORD
    ports:
      - "3333:22"
      - "8545:8545"
    volumes:
      - ./projects:/home/dragonfly/projects
    environment:
      - TZ="Etc/UTC"
    tty: true
    restart: unless-stopped
